-- ============================================
-- CLASSICMODELS SALES ANALYSIS
-- SQL PORTFOLIO PROJECT
-- ============================================


use classicmodels;

-- Q1 total revenue generated by the company

select 
   sum(quantityordered*priceeach) as 
total_revenue
from orderdetails;


-- Q2 top 10 products by revenue

select p.productname,
   sum(od.quantityordered*od.priceeach) as 
total_revenue
from products p
join orderdetails od
on od.productCode=p.productCode
group by p.productName
order by total_revenue desc
limit 10;



-- Q3 top 10 countries generate highest revenue

select c.country,sum(od.quantityordered*od.priceeach) as 
total_revenue
from customers c 
join orders o
on o.customerNumber=c.customerNumber
join orderdetails od 
on od.orderNumber=o.orderNumber
group by c.country
order by total_revenue desc
limit 10;



-- Q4 top 10 customers by revenue

select c.customername,sum(od.quantityordered*od.priceeach) as 
total_revenue
from customers c
join orders o
on o.customerNumber=c.customerNumber
join orderdetails od 
on od.orderNumber=o.orderNumber
group by c.customerNumber
order by total_revenue desc
limit 10;



select*from employees;
-- Q5 top 10 sales representative generates highest revenue 


select e.employeenumber,e.firstname,sum(od.quantityordered*od.priceeach) as 
total_revenue
from employees e
join customers c
on c.salesRepEmployeeNumber=e.employeeNumber
join orders o
on o.customerNumber=c.customerNumber
join orderdetails od 
on od.orderNumber=o.orderNumber
group by e.employeeNumber,e.firstName
order by total_revenue desc
limit 10;



-- Q6 customers who has never placed an order

select c.customernumber,c.customername
from customers c
left join orders o
on o.customerNumber=c.customerNumber
where o.orderNumber is null;


-- Q7 the product line generates the highest revenue


select pl.productline,sum(od.quantityordered*od.priceeach) as 
total_revenue
from productlines pl
join products p
on p.productline=pl.productLine
join orderdetails od
on od.productCode=p.productCode
group by pl.productline
order by total_revenue desc
limit 10;



-- Q8 which year generated the highest revenue

select year(o.orderdate),sum(od.quantityordered*od.priceeach) as 
total_revenue
from orders o
join orderdetails od
on od.orderNumber=o.orderNumber
group by year(o.orderdate)
order by total_revenue desc
limit 1;



-- Q9  WHICH MONTH GENERATED THE HIGHEST REVENUE


select month(o.orderdate),sum(od.quantityordered*od.priceeach) as 
total_revenue
from orders o
join orderdetails od
on od.orderNumber=o.orderNumber
group by month(o.orderdate)
order by total_revenue desc
limit 1;



-- Q10 Which customers have purchased the highest total quantity of products? (Top 10)

select c.customername,sum(od.quantityordered) 
as total_quantity
from customers c
join orders o
on o.customerNumber=c.customerNumber
join orderdetails od
on od.orderNumber=o.orderNumber
group by c.customername
order by total_quantity desc
limit 10;



-- Q11 top 10 customers based on no.of orders placed

select c.customername,count(o.ordernumber) as total_orders
from customers c
join orders o
on o.customerNumber=c.customerNumber
group by c.customerName
order by total_orders desc
limit 10;



-- Q12 TOP 10 PRODUCTS BASED ON THE TOTAL QUANTITY SOLD

select p.productname,sum(od.quantityordered) as products_sold
from products p
join orderdetails od 
on od.productCode=p.productCode
group by p.productName
order by products_sold desc
limit 10;



-- Q13  average order value for each customer

select c.customername,avg(od.quantityOrdered*od.priceeach) as average_order
from customers c
join orders o
on o.customerNumber=c.customerNumber
join orderdetails od 
on od.orderNumber=o.orderNumber
group by c.customername
order by average_order desc;



-- Q14 find customers whose total spending is greater than the average customer spending

SELECT
    c.customerName,
    SUM(od.quantityOrdered * od.priceEach) AS total_spent
FROM customers c
JOIN orders o
    ON c.customerNumber = o.customerNumber
JOIN orderdetails od
    ON o.orderNumber = od.orderNumber
GROUP BY c.customerNumber, c.customerName
HAVING SUM(od.quantityOrdered * od.priceEach) >
(
    SELECT AVG(customer_total)
    FROM
    (
        SELECT
            c2.customerNumber,
            SUM(od2.quantityOrdered * od2.priceEach) AS customer_total
        FROM customers c2
        JOIN orders o2
            ON c2.customerNumber = o2.customerNumber
        JOIN orderdetails od2
            ON o2.orderNumber = od2.orderNumber
        GROUP BY c2.customerNumber
    ) AS customer_totals
)
ORDER BY total_spent DESC;


-- Q15 Show total revenue for each month, across all years.

SELECT
    MONTHNAME(o.orderDate) AS month_name,
    SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM orders o
JOIN orderdetails od
    ON o.orderNumber = od.orderNumber
GROUP BY MONTH(o.orderDate), MONTHNAME(o.orderDate)
ORDER BY MONTH(o.orderDate);


-- Q16 TOP 10 PRODUCTS WITH THE HIGHEST AVERAGE SELLING PRICE

select p.productname, avg(od.priceeach) as avg_selling_price
from products p
join orderdetails od 
on od.productCode=p.productCode
group by p.productname
order by avg_selling_price desc
limit 10;


-- Q17 — Top 10 Highest-Value Orders

SELECT
    o.orderNumber,
    SUM(od.quantityOrdered * od.priceEach) AS order_value
FROM orders o
JOIN orderdetails od
    ON o.orderNumber = od.orderNumber
GROUP BY o.orderNumber
ORDER BY order_value DESC
LIMIT 10;



-- Q18 — Rank Customers by Revenue

SELECT
    c.customerName,
    SUM(od.quantityOrdered * od.priceEach) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(od.quantityOrdered * od.priceEach) DESC
    ) AS revenue_rank
FROM customers c
JOIN orders o
    ON c.customerNumber = o.customerNumber
JOIN orderdetails od
    ON o.orderNumber = od.orderNumber
GROUP BY c.customerNumber, c.customerName
ORDER BY revenue_rank;



-- Q19 — Yearly Revenue + Running Revenue

WITH yearly_sales AS (
    SELECT
        YEAR(o.orderDate) AS sales_year,
        SUM(od.quantityOrdered * od.priceEach) AS year_revenue
    FROM orders o
    JOIN orderdetails od
        ON o.orderNumber = od.orderNumber
    GROUP BY YEAR(o.orderDate)
)
SELECT
    sales_year,
    year_revenue,
    SUM(year_revenue) OVER (
        ORDER BY sales_year
    ) AS running_revenue
FROM yearly_sales
ORDER BY sales_year;



-- Q20 — Products Above Average Revenue

WITH product_sales AS (
    SELECT
        p.productCode,
        p.productName,
        SUM(od.quantityOrdered * od.priceEach) AS product_revenue
    FROM products p
    JOIN orderdetails od
        ON p.productCode = od.productCode
    GROUP BY p.productCode, p.productName
)
SELECT
    productName,
    product_revenue
FROM product_sales
WHERE product_revenue > (
    SELECT AVG(product_revenue)
    FROM product_sales
)
ORDER BY product_revenue DESC;





